parameters:
  - name: targets
    type: object
    # Unity -buildTarget command line args https://docs.unity3d.com/Manual/CommandLineArguments.html
    # Standalone, Win, Win64, OSXUniversal, Linux64, iOS, Android, WebGL, XboxOne, PS4, WindowsStoreApps, Switch, tvOS, Lumin
  - name: os
    type: object
    default:
      windows:
        pool: self-hosted-windows
        modules: '"windows-il2cpp", "universal-windows-platform", "lumin", "webgl", "android"'
        validTargets:
          - StandaloneWindows64 #Win64
          - WSAPlayer #WindowsStoreApps
          - Android
          - Lumin
          - WebGL
      macOS:
        pool: self-hosted-mac
        modules: '"mac-il2cpp", "ios", "webgl", "lumin", "android"'
        validTargets:
        - StandaloneOSX #OSXUniversal
        - iOS
        - Android
        - Lumin
        - WebGL
      linux:
        pool: self-hosted-linux
        modules: '"linux", "webgl", "lumin", "android"'
        validTargets:
        - StandaloneLinux64 #Linux64
        - Android
        - Lumin
        - WebGL

stages:
  - template: stages/unity-build.yml
    parameters:
      platform: windows
      targets: ${{ parameters.targets }}
      ${{ insert }}: ${{ parameters.os.windows }}
  - template: stages/publish.yml
